=== 459011Jeffrey/selinum-final-version/finalVersion/lib/basketball.dtd
<!ELEMENT basketball (player*,coach*,team*,match*)>
<!ELEMENT player (name,age,team_ref,games_played)>
<!ELEMENT coach (name,team_ref,performance)>
<!ELEMENT name (firstname,lastname)>
<!ELEMENT team (team_name,win_loss_record,player_ref*,coach_ref)>
<!ELEMENT match (teams,date,score)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT team_ref EMPTY>
<!ELEMENT games_played (#PCDATA)>
<!ELEMENT performance (wins,losses,ratio)>
<!ELEMENT wins (#PCDATA)>
<!ELEMENT losses (#PCDATA)>
<!ELEMENT ratio (#PCDATA)>
<!ELEMENT team_name (#PCDATA)>
<!ELEMENT win_loss_record (#PCDATA)>
<!ELEMENT player_ref EMPTY>
<!ELEMENT coach_ref EMPTY>
<!ELEMENT teams (home_team_ref,visitor_team_ref)>
<!ELEMENT home_team_ref EMPTY>
<!ELEMENT visitor_team_ref EMPTY>
<!ELEMENT date (#PCDATA)>
<!ELEMENT score (home_score,visitor_score,winner)>
<!ELEMENT home_score (#PCDATA)>
<!ELEMENT visitor_score (#PCDATA)>
<!ELEMENT winner (#PCDATA)>
<!ATTLIST player id ID #REQUIRED>
<!ATTLIST coach id ID #REQUIRED>
<!ATTLIST team id ID #REQUIRED>
<!ATTLIST match id ID #REQUIRED>
<!ATTLIST team_ref idref IDREF #REQUIRED>
<!ATTLIST player_ref idref IDREF #REQUIRED>
<!ATTLIST coach_ref idref IDREF #REQUIRED>
<!ATTLIST home_team_ref idref IDREF #REQUIRED>
<!ATTLIST visitor_team_ref idref IDREF #REQUIRED>

=== 459011Jeffrey/selinum-final-version/finalVersion/lib/file.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE basketball SYSTEM "basketball.dtd"><basketball><player id="p1"><name><firstname>Steven</firstname><lastname>Adams</lastname></name><age>26</age><team_ref idref="OKC"/><games_played>16</games_played></player><player id="p2"><name><firstname>Bam</firstname><lastname>Adebayo</lastname></name><age>22</age><team_ref idref="MIA"/><games_played>19</games_played></player><player id="p3"><name><firstname>LaMarcus</firstname><lastname>Aldridge</lastname></name><age>34</age><team_ref idref="SAS"/><games_played>20</games_played></player><player id="p4"><name><firstname>Nickeil</firstname><lastname>Alexander-Walker</lastname></name><age>21</age><team_ref idref="NOP"/><games_played>16</games_played></player><player id="p5"><name><firstname>Grayson</firstname><lastname>Allen</lastname></name><age>24</age><team_ref idref="MEM"/><games_played>10</games_played></player><player id="p6"><name><firstname>Jarrett</firstname><lastname>Allen</lastname></name><age>21</age><team_ref idref="BRK"/><games_played>20</games_played></player><player id="p7"><name><firstname>Kadeem</firstname><lastname>Allen</lastname></name><age>27</age><team_ref idref="NYK"/><games_played>1</games_played></player><player id="p8"><name><firstname>Al-Farouq</firstname><lastname>Aminu</lastname></name><age>29</age><team_ref idref="ORL"/><games_played>18</games_played></player><player id="p9"><name><firstname>Kyle</firstname><lastname>Anderson</lastname></name><age>26</age><team_ref idref="MEM"/><games_played>17</games_played></player><player id="p10"><name><firstname>Ryan</firstname><lastname>Anderson</lastname></name><age>31</age><team_ref idref="HOU"/><games_played>2</games_played></player><player id="p11"><name><firstname>Giannis</firstname><lastname>Antetokounmpo</lastname></name><age>25</age><team_ref idref="MIL"/><games_played>21</games_played></player><player id="p12"><name><firstname>Kostas</firstname><lastname>Antetokounmpo</lastname></name><age>22</age><team_ref idref="LAL"/><games_played>2</games_played></player><player id="p13"><name><firstname>Thanasis</firstname><lastname>Antetokounmpo</lastname></name><age>27</age><team_ref idref="MIL"/><games_played>4</games_played></player><player id="p14"><name><firstname>Carmelo</firstname><lastname>Anthony</lastname></name><age>35</age><team_ref idref="POR"/><games_played>6</games_played></player><player id="p15"><name><firstname>OG</firstname><lastname>Anunoby</lastname></name><age>22</age><team_ref idref="TOR"/><games_played>18</games_played></player><player id="p16"><name><firstname>Ryan</firstname><lastname>Arcidiacono</lastname></name><age>25</age><team_ref idref="CHI"/><games_played>21</games_played></player><player id="p17"><name><firstname>Trevor</firstname><lastname>Ariza</lastname></name><age>34</age><team_ref idref="SAC"/><games_played>12</games_played></player><player id="p18"><name><firstname>D.J.</firstname><lastname>Augustin</lastname></name><age>32</age><team_ref idref="ORL"/><games_played>19</games_played></player><player id="p19"><name><firstname>Deandre</firstname><lastname>Ayton</lastname></name><age>21</age><team_ref idref="PHO"/><games_played>1</games_played></player><player id="p20"><name><firstname>Dwayne</firstname><lastname>Bacon</lastname></name><age>24</age><team_ref idref="CHO"/><games_played>16</games_played></player><player id="p21"><name><firstname>Marvin</firstname><lastname>Bagley</lastname></name><age>20</age><team_ref idref="SAC"/><games_played>1</games_played></player><player id="p22"><name><firstname>Lonzo</firstname><lastname>Ball</lastname></name><age>22</age><team_ref idref="NOP"/><games_played>12</games_played></player><player id="p23"><name><firstname>Mo</firstname><lastname>Bamba</lastname></name><age>21</age><team_ref idref="ORL"/><games_played>17</games_played></player><player id="p24"><name><firstname>J.J.</firstname><lastname>Barea</lastname></name><age>35</age><team_ref idref="DAL"/><games_played>3</games_played></player><player id="p25"><name><firstname>Harrison</firstname><lastname>Barnes</lastname></name><age>27</age><team_ref idref="SAC"/><games_played>19</games_played></player><player id="p26"><name><firstname>RJ</firstname><lastname>Barrett</lastname></name><age>19</age><team_ref idref="NYK"/><games_played>20</games_played></player><player id="p27"><name><firstname>Will</firstname><lastname>Barton</lastname></name><age>29</age><team_ref idref="DEN"/><games_played>15</games_played></player><player id="p28"><name><firstname>Keita</firstname><lastname>Bates-Diop</lastname></name><age>24</age><team_ref idref="MIN"/><games_played>8</games_played></player><player id="p29"><name><firstname>Nicolas</firstname><lastname>Batum</lastname></name><age>31</age><team_ref idref="CHO"/><games_played>11</games_played></player><player id="p30"><name><firstname>Aron</firstname><lastname>Baynes</lastname></name><age>33</age><team_ref idref="PHO"/><games_played>13</games_played></player><player id="p31"><name><firstname>Kent</firstname><lastname>Bazemore</lastname></name><age>30</age><team_ref idref="POR"/><games_played>20</games_played></player><player id="p32"><name><firstname>Darius</firstname><lastname>Bazley</lastname></name><age>19</age><team_ref idref="OKC"/><games_played>19</games_played></player><player id="p33"><name><firstname>Bradley</firstname><lastname>Beal</lastname></name><age>26</age><team_ref idref="WAS"/><games_played>18</games_played></player><player id="p34"><name><firstname>Malik</firstname><lastname>Beasley</lastname></name><age>23</age><team_ref idref="DEN"/><games_played>13</games_played></player><player id="p35"><name><firstname>Marco</firstname><lastname>Belinelli</lastname></name><age>33</age><team_ref idref="SAS"/><games_played>20</games_played></player><player id="p36"><name><firstname>Jordan</firstname><lastname>Bell</lastname></name><age>25</age><team_ref idref="MIN"/><games_played>9</games_played></player><player id="p37"><name><firstname>DeAndre'</firstname><lastname>Bembry</lastname></name><age>25</age><team_ref idref="ATL"/><games_played>21</games_played></player><player id="p38"><name><firstname>Dragan</firstname><lastname>Bender</lastname></name><age>22</age><team_ref idref="MIL"/><games_played>3</games_played></player><player id="p39"><name><firstname>Dāvis</firstname><lastname>Bertāns</lastname></name><age>27</age><team_ref idref="WAS"/><games_played>18</games_played></player><player id="p40"><name><firstname>Patrick</firstname><lastname>Beverley</lastname></name><age>31</age><team_ref idref="LAC"/><games_played>19</games_played></player><player id="p41"><name><firstname>Khem</firstname><lastname>Birch</lastname></name><age>27</age><team_ref idref="ORL"/><games_played>10</games_played></player><player id="p42"><name><firstname>Goga</firstname><lastname>Bitadze</lastname></name><age>20</age><team_ref idref="IND"/><games_played>15</games_played></player><player id="p43"><name><firstname>Bismack</firstname><lastname>Biyombo</lastname></name><age>27</age><team_ref idref="CHO"/><games_played>20</games_played></player><player id="p44"><name><firstname>Nemanja</firstname><lastname>Bjelica</lastname></name><age>31</age><team_ref idref="SAC"/><games_played>19</games_played></player><player id="p45"><name><firstname>Eric</firstname><lastname>Bledsoe</lastname></name><age>30</age><team_ref idref="MIL"/><games_played>21</games_played></player><player id="p46"><name><firstname>Bogdan</firstname><lastname>Bogdanović</lastname></name><age>27</age><team_ref idref="SAC"/><games_played>18</games_played></player><player id="p47"><name><firstname>Bojan</firstname><lastname>Bogdanović</lastname></name><age>30</age><team_ref idref="UTA"/><games_played>20</games_played></player><player id="p48"><name><firstname>Jonah</firstname><lastname>Bolden</lastname></name><age>24</age><team_ref idref="PHI"/><games_played>2</games_played></player><player id="p49"><name><firstname>Jordan</firstname><lastname>Bone</lastname></name><age>22</age><team_ref idref="DET"/><games_played>3</games_played></player><player id="p50"><name><firstname>Isaac</firstname><lastname>Bonga</lastname></name><age>20</age><team_ref idref="WAS"/><games_played>13</games_played></player><player id="p51"><name><firstname>Devin</firstname><lastname>Booker</lastname></name><age>23</age><team_ref idref="PHO"/><games_played>19</games_played></player><player id="p52"><name><firstname>Chris</firstname><lastname>Boucher</lastname></name><age>27</age><team_ref idref="TOR"/><games_played>17</games_played></player><player id="p53"><name><firstname>Brian</firstname><lastname>Bowen</lastname></name><age>21</age><team_ref idref="IND"/><games_played>3</games_played></player><player id="p54"><name><firstname>Ky</firstname><lastname>Bowman</lastname></name><age>22</age><team_ref idref="GSW"/><games_played>22</games_played></player><player id="p55"><name><firstname>Avery</firstname><lastname>Bradley</lastname></name><age>29</age><team_ref idref="LAL"/><games_played>10</games_played></player><player id="p56"><name><firstname>Tony</firstname><lastname>Bradley</lastname></name><age>22</age><team_ref idref="UTA"/><games_played>15</games_played></player><player id="p57"><name><firstname>Jarrell</firstname><lastname>Brantley</lastname></name><age>23</age><team_ref idref="UTA"/><games_played>1</games_played></player><player id="p58"><name><firstname>Ignas</firstname><lastname>Brazdeikis</lastname></name><age>21</age><team_ref idref="NYK"/><games_played>6</games_played></player><player id="p59"><name><firstname>Mikal</firstname><lastname>Bridges</lastname></name><age>23</age><team_ref idref="PHO"/><games_played>19</games_played></player><player id="p60"><name><firstname>Miles</firstname><lastname>Bridges</lastname></name><age>21</age><team_ref idref="CHO"/><games_played>22</games_played></player><player id="p61"><name><firstname>Oshae</firstname><lastname>Brissett</lastname></name><age>21</age><team_ref idref="TOR"/><games_played>4</games_played></player><player id="p62"><nam
